### ISSUE TITLE
Implement live tracking - list view mode

### ISSUE THREAD

**Issue by leekhai18** [park-eco/park-eco-mobile-manager#5]
Implement live tracking screen with list view mode.
Here is the list view mode wireframe:
![3-livetracking-modelist](https://user-images.githubusercontent.com/26641870/47252663-9969ad00-d472-11e8-9444-5f51341be5f8.png)

**Comment by leekhai18** [comment]
This is my design. It has:
- Animated search bar
- A status sorting button is implemented 
- A navigation button to open Drawer
Here is this:
<img width="425" alt="screen shot 2018-10-20 at 5 27 24 pm" src="https://user-images.githubusercontent.com/26641870/47254520-e6a74800-d48d-11e8-9235-c829aff81024.png">

**Comment by nguyenlamlll** [comment]
@leekhai18 What does `Status` mean in this case? Does it the current capacity of the parking lot?
Say, 500/1000 => 50%, right?

**Comment by leekhai18** [comment]
Status = current number/ total
